language: python
python:
    - '2.7'
sudo: required
services:
  - docker
before_install:
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine
  - sudo pip install docker-compose
  - sudo pip install tox
  - sudo service rabbitmq-server stop
  - sudo service docker restart
  - docker info
  - docker ps -a
script:
  - tox -r
  - docker-compose -f docker-compose-integration-tests.yml build
  - docker-compose -f docker-compose-integration-tests.yml up -d api collector messaging database
  - docker-compose -f docker-compose-integration-tests.yml up test
deploy:
  provider: pypi
  user: internaphosting
  on:
    tags: true
    repo: internap/almanach
  password:
    secure: DNUJwYFBybq5qw7WMYQOoU/cWEsLwRMXD+Fjl6Ou+VwxwDiX+vsS4GIaq/EjFFqqDVMTMG0eEJlIyRvW9OVOAhNDl4QqdadojX1pqAurncLJEmd9EjJlhbbwOd64BNV+0bwj3GkFr74aa0VmGm9d9Ut5lkgMnAWA/EFTPzsTJSV/fTRrkifRCH69asQfBxOcUWrMrA3u2z0xNxFaHjcVMp16cG6j83VPYRolzW7HF87vt0+DCak8XL1XmuW0kM+zCWHYooO5pOV+6ILgR0jI/Emi3zHT60zDhvm3JtGbt2d++isTaRyYulAt8qm/kZGEq5VC/fq0tAebwtFyx91yx++5agADkxf6H70znwu4IZnpj245qhI1L9JZn0Tk0IzzwCDqaJSfddSC0qQHO8iEa4SCbEfp1vKMFoXZ3E2Y31rlGpbwntAHFvq78uqWvLsNwpR/tAW8RGKNUtkPu91rcuYfixxX8EoH68DtmHmTQ7DDK4SMJqj44hKZu6h2ea4AhgapuG8SaZjmnuCorIherYR6TEe4r52wzxSVGCu8JSjYM4jawz21/U+HKcpTPMmqT9tbGDK731lZeOM4mFxu9kkwM+bdcdPx6zb7M0lJLbgDQaP34jNYq2m1+YrIV0abhxnHM3FuWcBzfE8ZIe8W45goyfChx8vaiUDpUMK8l6U=
