version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: api
    environment:
      MONGODB_URL: ${MONGODB_URL}
    ports:
      - "80:8000"
  collector:
    build:
      context: .
      dockerfile: Dockerfile
    command: collector
    environment:
      MONGODB_URL: ${MONGODB_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
